version: 1.0-{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
configuration: Release
platform: Any CPU
image: Visual Studio 2017


before_build:
- cmd: >-   
    nuget restore

build:
  project: Wooting.NET.sln
  verbosity: minimal

artifacts:
  - path: Wooting.NET/bin/Release/netstandard2.0
    name: Wooting.NET.1.0-v$(appveyor_build_version)
    type: zip
